#!/bin/bash
#
# Copyright (C) 2008-2009 SecurixLive   <dev@securixlive.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License Version 2 as
# published by the Free Software Foundation.  You may not use, modify or
# distribute this program under any other version of the GNU General
# Public License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
#
# Location: /etc/init.d/nsm-server
#
# Description:
#   Process control for all of the NSM server components.
#

case $1 in
    start)
        nsm --server --start
		;;
    stop)
        nsm --server --stop
		;;
    restart)
        nsm --server --restart
		;;
    status)
		nsm --server --status
		;;
    *)
        echo "Usage: $0 start|stop|restart|status"
		exit 1
        ;;
esac

exit 0
