#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018,2019,2020 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Ensure we're running as root
if [ "$(id -u)" != 0 ]; then
        echo "ERROR: This script must run as root.  Hint..." 1>&2
        echo "  sudo $0 $@" 1>&2
        exit 1
fi

# /etc/nsm/securityonion.conf defines the limited user that we use for starting zeekctl
SO_CONF="/etc/nsm/securityonion.conf"

# Add new Bro entries to SO_CONF if necessary
if ! grep BRO_USER $SO_CONF >/dev/null; then
	echo >> $SO_CONF
	echo "# BRO_USER specifies the user account used to start Bro." >> $SO_CONF
	echo "BRO_USER=sguil"	>> $SO_CONF
	echo "BRO_GROUP=sguil"	>> $SO_CONF
fi

# load in user config
. $SO_CONF

# Run "zeekctl" as Bro user and pass along arguments
su $BRO_USER -c "/opt/bro/bin/zeekctl $@" 2>&1 | grep -v "warning: new .* version detected" | grep -v "Warning: ZeekControl plugin uses legacy BroControl API. Use" | grep -v "'import ZeekControl.plugin' instead of 'import BroControl.plugin'" | grep -v "^$" | grep -v "^Warning: Plugin 'af_packet' uses deprecated method 'broctl_config'; use 'zeekctl_config' instead$"
