#!/bin/bash
#
# Copyright (C) 2008-2009 SecurixLive   <dev@securixlive.com>
# Modified by Doug Burks for Security Onion
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License Version 2 as
# published by the Free Software Foundation.  You may not use, modify or
# distribute this program under any other version of the GNU General
# Public License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#

#
# INCLUDES
#
INC="/etc/nsm/administration.conf"
. $INC

. $NSM_LIB_DIR/lib-console-utils
. $NSM_LIB_DIR/lib-nsm-common-utils
. $NSM_LIB_DIR/lib-nsm-server-utils

# ensure we are root user before continuing any further
is_root
if [ "${?}" -ne 0 ]
then
	echo_error_msg 0 "OOPS: Must be root to run this script!"
	exit 1;
fi
	
SERVER_NAME="securityonion"

# check that the server DOES exist via its config
if [ ! -f "/etc/nsm/${SERVER_NAME}/server.conf" ]
then
	echo_error_msg 0 "OOPS: The server \"${SERVER_NAME}\" does not exist!"
	exit 1
else
	# load existing variables for the server
	. /etc/nsm/${SERVER_NAME}/server.conf
fi

mysql --defaults-file=/etc/mysql/debian.cnf -Dsecurityonion_db -e 'select uid,username,email,last_login,tzoffset from user_info where username != "auto" and password != "LOCKED";'

exit 0

