#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Define initial variables
SENSORTAB="/etc/nsm/sensortab"
NUM_INTERFACES=$(grep -v "#" ${SENSORTAB} 2>/dev/null | wc -l)

# If there are no sensor interfaces enabled, then exit
if [ ${NUM_INTERFACES} -eq 0 ]; then
	exit 1
fi

sleep 1

date >> /var/log/nsm/sensor-newday-argus.log
/usr/sbin/nsm --sensor --restart --only-argus >> /var/log/nsm/sensor-newday-argus.log

date >> /var/log/nsm/sensor-newday-http-agent.log
/usr/sbin/nsm --sensor --restart --only-http-agent >> /var/log/nsm/sensor-newday-http-agent.log

sleep 1

date >> /var/log/nsm/sensor-newday-pcap.log
/usr/sbin/nsm --sensor --restart --only-pcap >> /var/log/nsm/sensor-newday-pcap.log
