#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if ! [ -f /opt/bro/etc/node.cfg ]; then
	exit 1
fi

SO_CONF="/etc/nsm/securityonion.conf"

# Add new Bro entries to SO_CONF if necessary
if ! grep BRO_USER $SO_CONF >/dev/null; then
	echo >> $SO_CONF
	echo "# BRO_USER specifies the user account used to start Bro." >> $SO_CONF
	echo "BRO_USER=sguil"	>> $SO_CONF
	echo "BRO_GROUP=sguil"	>> $SO_CONF
fi

# load in user config
. $SO_CONF

if ! [ "$BRO_ENABLED" == "yes" ]; then
	exit 0
fi

# Run "broctl cron" as Bro user
su $BRO_USER -c '/opt/bro/bin/broctl cron'
