#!/bin/bash

# Define initial variables
SENSORTAB="/etc/nsm/sensortab"
NUM_INTERFACES=$(grep -v "#" ${SENSORTAB} 2>/dev/null | wc -l)

# If there are no sensor interfaces enabled, then exit
if [ ${NUM_INTERFACES} -eq 0 ]; then
	exit 1
fi

SO_CONF="/etc/nsm/securityonion.conf"

# Add new Bro entries to SO_CONF if necessary
if ! grep BRO_USER $SO_CONF >/dev/null; then
	echo >> $SO_CONF
	echo "# BRO_USER specifies the user account used to start Bro." >> $SO_CONF
	echo "BRO_USER=sguil"	>> $SO_CONF
	echo "BRO_GROUP=sguil"	>> $SO_CONF
fi

# load in user config
. $SO_CONF

if [ "$BRO_ENABLED" == "yes" ]; then

	# Set ownership of Bro directories to Bro user.
	# Large sensors with lots of Bro logs can take longer than 5 minutes to chown.
	# This can result in the cron jobs piling up.
	# Commenting this out for now.
	#chown -R $BRO_USER:$BRO_GROUP /nsm/bro >/dev/null 2>&1

	# Run "broctl cron" as Bro user
	su $BRO_USER -c '/opt/bro/bin/broctl cron'
fi
