#!/bin/bash

LOG="/var/log/nsm/watchdog.log"

# If server enabled, then check if stale
FILE="/etc/nsm/servertab"
ENABLED=$(grep -v "#" ${FILE} 2>/dev/null | wc -l)
if [ ${ENABLED} -gt 0 ]; then
	$OUTPUT=$(/usr/sbin/nsm_server_ps-restart --if-stale)
	if [ "${OUTPUT}" != "" ]; then
		echo "$(date) ${OUTPUT}" >> ${LOG}
	fi
fi

# If there are sensor interfaces enabled, then check if stale
FILE="/etc/nsm/sensortab"
ENABLED=$(grep -v "#" ${FILE} 2>/dev/null | wc -l)
if [ ${ENABLED} -gt 0 ]; then
	$OUTPUT=$(/usr/sbin/nsm_sensor_ps-restart --if-stale)
	if [ "${OUTPUT}" != "" ]; then
		echo "$(date) ${OUTPUT}" >> ${LOG}
	fi
fi
