#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

LOG="/var/log/nsm/watchdog.log"

# If server enabled, then check if stale
FILE="/etc/nsm/servertab"
ENABLED=$(grep -v "#" ${FILE} 2>/dev/null | wc -l)
if [ ${ENABLED} -gt 0 ]; then
	OUTPUT=$(/usr/sbin/nsm_server_ps-restart --if-stale)
	if [ "${OUTPUT}" != "" ]; then
		echo "$(date) ${OUTPUT}" >> ${LOG}
	fi
fi

# If there are sensor interfaces enabled, then check if stale
FILE="/etc/nsm/sensortab"
ENABLED=$(grep -v "#" ${FILE} 2>/dev/null | wc -l)
if [ ${ENABLED} -gt 0 ]; then
	OUTPUT=$(/usr/sbin/nsm_sensor_ps-restart --if-stale)
	if [ "${OUTPUT}" != "" ]; then
		echo "$(date) ${OUTPUT}" >> ${LOG}
	fi
fi
