#!/bin/bash

# Define initial variables
SENSORTAB="/etc/nsm/sensortab"
NUM_INTERFACES=$(grep -v "#" ${SENSORTAB} 2>/dev/null | wc -l)
INTERFACES=$(grep -v '#' $SENSORTAB | awk '{print $1}')
LOG="/var/log/nsm/netsniff-sync.log"
NEED_TO_RESTART="no"
OS_DATE=$(date +"%Y-%m-%d")
OS_TIME=$(date +"%H%M")

# If there are no sensor interfaces enabled, then exit
if [ ${NUM_INTERFACES} -eq 0 ]; then
        exit 1
fi

if [ $OS_TIME -eq 0000 ]; then
	echo "$(date) Time is 00:00, so skipping check for netsniff date since /etc/cron.d/sensor-newday should be restarting it anyway." >> $LOG
	exit 0
fi

# Check all enabled sniffing interfaces
for i in $INTERFACES; do
	# Check to see if pcap has been enabled on that interface
	if grep -q 'PCAP_ENABLED="yes"' /etc/nsm/$i/sensor.conf; then
		# Check to see if netsniff-ng is running on that interface
       		if pgrep -af netsniff-ng.*/nsm/sensor_data/$i > /dev/null 2>&1; then
       			NETSNIFF_DATE=$(pgrep -af netsniff-ng.*/nsm/sensor_data/$i | cut -d'/' -f6)
			# Check to see if netsniff's date matches current OS date
        		if [ "$NETSNIFF_DATE" != "$OS_DATE" ]; then
				NEED_TO_RESTART="yes"
			fi
		fi
	fi
done

# Due to Issue 1118, if we try to restart pcap on a single interface, it will also restart Bro:
# https://github.com/Security-Onion-Solutions/security-onion/issues/1118
# To avoid this, we'll just restart all pcap instances.
# This is probably a good idea anyway since, in most cases, if one netsniff instance is recording to the wrong date, then all of them are.
if [ "$NEED_TO_RESTART" == "yes" ]; then
	echo "$(date) netsniff-ng date mismatch detected.  Restarting all netsniff-ng instances." >> $LOG
	nsm_sensor_ps-restart --only-pcap >> $LOG 2>&1
fi
