#!/bin/bash

# Define initial variables
SENSORTAB="/etc/nsm/sensortab"
NUM_INTERFACES=$(grep -v "#" ${SENSORTAB} 2>/dev/null | wc -l)

# If there are no sensor interfaces enabled, then exit
if [ ${NUM_INTERFACES} -eq 0 ]; then
	exit 1
fi

( date ; /usr/sbin/nsm_server_ps-restart --if-stale ; /usr/sbin/nsm_sensor_ps-restart --if-stale) >> /var/log/nsm/watchdog.log
