#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /usr/sbin/so-nsm-common

# If server not enabled, then exit
FILE="/etc/nsm/servertab"
ENABLED=$(grep -v "#" ${FILE} 2>/dev/null | wc -l)
if [ ${ENABLED} -eq 0 ]; then
	exit 1
fi

# If logrotate script doesn't already exist, create it
FILE="/etc/logrotate.d/so-server-backup-config"
if ! [ -f ${FILE} ]; then
cat << EOF > ${FILE}
/var/log/nsm/so-server-backup-config.log {
    weekly
    rotate 4
    copytruncate
    compress
    missingok
    notifempty
}
EOF
fi

# Set defaults
SERVER_CONFIG_BACKUPS=10
SERVER_CONFIG_BACKUP_DIR="/etc/nsm/backup"

# User can override defaults in securityonion.conf
. /etc/nsm/securityonion.conf

# Make sure the backup directory exists
mkdir -p ${SERVER_CONFIG_BACKUP_DIR}

# Create a backup of the server config
/usr/sbin/nsm_server_backup-config --force-yes --server-name=securityonion --backup-file=${SERVER_CONFIG_BACKUP_DIR}/securityonion-server-backup-`date +\%Y-\%m-\%d`.tar.gz

# If old backups exist, delete them
if ls ${SERVER_CONFIG_BACKUP_DIR}/*server-backup*.tar.gz >/dev/null 2>&1; then
	/usr/bin/find ${SERVER_CONFIG_BACKUP_DIR}/*server-backup*.tar.gz -mtime +${SERVER_CONFIG_BACKUPS} -exec rm -f {} \;
fi
