#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /usr/sbin/so-nsm-common

# If there are no sensor interfaces enabled, then exit
FILE="/etc/nsm/sensortab"
ENABLED=$(grep -v "#" ${FILE} 2>/dev/null | wc -l)
if [ ${ENABLED} -eq 0 ]; then
	exit 1
fi

# If logrotate script doesn't already exist, create it
FILE="/etc/logrotate.d/so-sensor-backup-config"
if ! [ -f ${FILE} ]; then
cat << EOF > ${FILE}
/var/log/nsm/so-sensor-backup-config.log {
    weekly
    rotate 4
    copytruncate
    compress
    missingok
    notifempty
}
EOF
fi

# Set defaults
SENSOR_CONFIG_BACKUPS=10
SENSOR_CONFIG_BACKUP_DIR="/etc/nsm/backup"

# User can override defaults in securityonion.conf
. /etc/nsm/securityonion.conf

# Make sure the backup directory exists
mkdir -p ${SENSOR_CONFIG_BACKUP_DIR}

# Create a backup for each sensor interface
for SENSOR in $(cat /etc/nsm/sensortab | grep -v '#' | awk '{print $1}'); do 
	/usr/sbin/nsm_sensor_backup-config --force-yes --sensor-name=${SENSOR} --backup-file=${SENSOR_CONFIG_BACKUP_DIR}/${SENSOR}-sensor-backup-`date +\%Y-\%m-\%d`.tar.gz
done

# If old backups exist, delete them
if ls ${SENSOR_CONFIG_BACKUP_DIR}/*sensor-backup*.tar.gz >/dev/null 2>&1; then
	/usr/bin/find ${SENSOR_CONFIG_BACKUP_DIR}/*sensor-backup*.tar.gz -mtime +${SENSOR_CONFIG_BACKUPS} -exec rm -f {} \;
fi
